//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValueWallet.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ValueWallet.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TitleOnBoardingStep1 {
            get {
                return ResourceManager.GetString("TitleOnBoardingStep1", resourceCulture);
            }
        }
        
        internal static string DetailOnBoardingStep1 {
            get {
                return ResourceManager.GetString("DetailOnBoardingStep1", resourceCulture);
            }
        }
        
        internal static string TitleOnBoardingStep2 {
            get {
                return ResourceManager.GetString("TitleOnBoardingStep2", resourceCulture);
            }
        }
        
        internal static string DetailOnBoardingStep2 {
            get {
                return ResourceManager.GetString("DetailOnBoardingStep2", resourceCulture);
            }
        }
        
        internal static string TitleOnBoardingStep3 {
            get {
                return ResourceManager.GetString("TitleOnBoardingStep3", resourceCulture);
            }
        }
        
        internal static string DetailOnBoardingStep3 {
            get {
                return ResourceManager.GetString("DetailOnBoardingStep3", resourceCulture);
            }
        }
    }
}
